**Wine_Dataset_KNN**

In [72]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [73]:
red = pd.read_csv(r"C:\Users\LaptopWala\Downloads\archive (3)\winequality_red.csv")
white = pd.read_csv(r"C:\Users\LaptopWala\Downloads\archive (3)\winequality_white.csv")
red['type'] = 'red'
white['type'] = 'white'
df= pd.concat([red, white], ignore_index=True)
df['type']= df['type'].map({'red': 0, 'white': 1})
df.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5,0
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5,0
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7,0
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7,0
9,7.5,0.50,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5,0

**duplicate rows**

In [74]:
num_dup = df.duplicated().sum()
print(f"Number of duplicate rows: {num_dup}")

Number of duplicate rows: 1177

In [75]:
df = df.drop_duplicates()

In [76]:
after_dup = df.duplicated().sum()
print(f"Number of duplicate rows after dropping duplicates: {after_dup}")

Number of duplicate rows after dropping duplicates: 0

In [77]:
df.reset_index(drop = True, inplace = True)
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5,0

In [78]:
X= df.drop('quality', axis=1)
y= df['quality']

In [89]:
y.value_counts()

quality
6    2323
5    1752
7     856
4     206
8     148
3      30
9       5
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [99]:
df.loc[:, 'quality'] = df['quality'].apply(lambda x: 1 if x >= 6 else 0)

In [100]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [105]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5,weights = 'uniform'  )
knn.fit(X_train_scaled, y_train)
y_pred = knn.predict(X_test_scaled)
train_score = knn.score(X_train_scaled, y_train)    
test_score = knn.score(X_test_scaled, y_test)
print("Train Score:", train_score)
print("Test Score:", test_score)
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Train Score: 0.8181390977443609
Test Score: 0.7302631578947368
Accuracy Score: 0.7302631578947368
Classification Report:
              precision    recall  f1-score   support

           0       0.66      0.58      0.62       398
           1       0.77      0.82      0.79       666

    accuracy                           0.73      1064
   macro avg       0.71      0.70      0.70      1064
weighted avg       0.73      0.73      0.73      1064

Confusion Matrix:
[[232 166]
 [121 545]]